config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#about'

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  get '/restaurants', to: 'restaurants#index'
  get '/restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  post '/restaurants', to: 'restaurants#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  RESTAURANTS = {
    1 => { name: "Dishoom", address: "Shoreditch, London", category: "indian" },
    2 => { name: "Sushi Samba", address: "City, London", category: "japanese" },
    3 => { name: "Kitaro", address: "City, São Luís", category: "japanese" }
  }

  def index
    if params[:food_type].blank?
      @restaurants = RESTAURANTS 
    else
      @restaurants = RESTAURANTS.select { |id, restaurant| restaurant[:category] == params[:food_type] }
    end
  end

  def create
    raise
  end

  def show
    @restaurant = RESTAURANTS[params[:id].to_i]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>The Spoon</h1>
    <%= yield %>
    <footer>Built at Le Wagon</footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About our Team!</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/restaurants/index.html.erb
<h2>Restaurants List</h2>

<form action="/restaurants" method="post">
  <h3>New Restaurant</h3>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>
<br>
<hr>
<br>

<%# 1. Dishoon %>
<%# 2. Sushi Samba %>
<%  %> <%# For ruby code in general %>
<%=  %> <%# For ruby code when printing %>
<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<ul>
  <% @restaurants.each do |id, restaurant| %>
    <li>
      <strong><%= id %>.</strong>
      <%= restaurant[:name] %>
      <%= link_to 'more info', restaurant_path(id) %>
      (<%= restaurant[:category] %>)
    </li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<h1><%= @restaurant[:name] %></h1>